import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import ClientProviders from "@/providers/ClientProviders";

const switzer = localFont({
	src: [
		{
			path: "../../public/fonts/Switzer_Complete/Fonts/TTF/Switzer-Variable.ttf",
			style: "normal",
		},
		{
			path: "../../public/fonts/Switzer_Complete/Fonts/TTF/Switzer-VariableItalic.ttf",
			style: "italic",
		},
	],
	variable: "--font-switzer",
	display: "swap",
});

const clashDisplay = localFont({
	src: "../../public/fonts/ClashGrotesk_Complete/Fonts/TTF/ClashGrotesk-Variable.ttf",
	variable: "--font-clash-display",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${switzer.variable} ${clashDisplay.variable} antialiased`}
			>
				<ClientProviders>
					<ThemeProvider
						attribute="class"
						defaultTheme="light"
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
				</ClientProviders>
			</body>
		</html>
	);
}
